### PR TITLE
Layer config updates

### PR DESCRIPTION
**Pull request by michaelpnelson**
link to demo deployment of your smk based app is 
 https://smk-clean-bc-rt-b16795-dev.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @dgboss, @NicoledeGreef

### CODE REVIEW

**Comment by michaelpnelson** [comment]
I'll close this and reopen to retrigger a deploy.

**Comment by michaelpnelson** [comment]
The failure in our Action is not making sense to me ...

x Error [400] Validation Errors:
        Invalid base entity _format_version: undefined

... so in the hopes it's a one-off, I'll close and reopen this to trigger it again ...

**Comment by michaelpnelson** [comment]
Now that a potential fix (https://github.com/bcgov/smk-actions/pull/15) has been merged, I'll close and reopen this to trigger another deploy and see if it's more successful.

**Comment by dgboss** [comment]
The Vanity URL for the dev deploy is https://smk-clean-bc-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @dgboss, @NicoledeGreef

**Comment by dgboss** [comment]
link to demo deployment of your smk based app is 
 https://smk-clean-bc-rt-b16795-prod.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @dgboss, @NicoledeGreef

**Comment by dgboss** [comment]
link to demo deployment of your smk based app is 
 https://smk-clean-bc-rt-b16795-prod.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @dgboss, @NicoledeGreef

**Comment by dgboss** [comment]
The Vanity URL for the prod deploy is https://smk-clean-bc.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @dgboss, @NicoledeGreef

**Pull request merged**
