### PR TITLE
Change Charging Stations layer from Esri Feature to GeoJSON

### PR DESCRIPTION
**Pull request by michaelpnelson**
link to demo deployment of your smk based app is 
 https://smk-clean-bc-rt-b16795-dev.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @dgboss, @NicoledeGreef

### CODE REVIEW

**Comment by dgboss** [comment]
The Vanity URL for the dev deploy is https://smk-clean-bc-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @dgboss, @NicoledeGreef

**Review by rustyjux — APPROVED** [review]
Gosh I hope you didn't have to do all those attribute entries/tweaks by hand!

Looks good. You know I like all the layers showing consistently in the legend :)

As you probably know, the draw order remains inconsistent - if I toggle layers off/on, then that layer will be on top.

**Comment by rustyjux** [comment]
re attributes, looking at the data dictionary (https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/all/#fuel-station-record-fields) and the fields shown...

- I think an important attribute to bump up would be EV Connector Type - if we could present it in plain text, rather than as a list/array that would be prettier
- I reckon the two French fields can go - our app is not attempting to be bilingual in any other way
- Also Geocode Status can go. OR convert values using a dictionary - e.g. 200-9 --> Point, 200-8 --> Address
- EV DC Fast number (and similary ev_level1 or 2_num) is the number of ports of that type. Maybe this could be expressed better as '# of DC Fast Ports', '# of Level 2 Ports'. Or reworked into a single field e.g.: Level 2 (3 ports), Level 1 (5 ports)
- Access Detail Code is redundant with Groups With Access Code
- Owner Type Code seems unnecessary
- Open Date seems unneeded

---

And one more legend thing - I think Identify Edit Search Area can be hidden

**Comment by michaelpnelson** [comment]
> re attributes, looking at the data dictionary (https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/all/#fuel-station-record-fields) and the fields shown...
> 
> * I think an important attribute to bump up would be EV Connector Type - if we could present it in plain text, rather than as a list/array that would be prettier
> * I reckon the two French fields can go - our app is not attempting to be bilingual in any other way
> * Also Geocode Status can go. OR convert values using a dictionary - e.g. 200-9 --> Point, 200-8 --> Address
> * EV DC Fast number (and similary ev_level1 or 2_num) is the number of ports of that type. Maybe this could be expressed better as '# of DC Fast Ports', '# of Level 2 Ports'. Or reworked into a single field e.g.: Level 2 (3 ports), Level 1 (5 ports)
> * Access Detail Code is redundant with Groups With Access Code
> * Owner Type Code seems unnecessary
> * Open Date seems unneeded
> 
> And one more legend thing - I think Identify Edit Search Area can be hidden

Thanks for these suggestions. I'll call these out in the Issue and ask for client feedback. 

We are limited in what we can do with formatting values. There are some options (https://bcgov.github.io/smk/docs/configuration/layers/attribute#format-property) - I've already applied "asLink()" - but we don't yet have support for formatting arrays or using a dictionary. This would have to be done in SMK.

**Comment by dgboss** [comment]
link to demo deployment of your smk based app is 
 https://smk-clean-bc-rt-b16795-prod.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @dgboss, @NicoledeGreef

**Comment by dgboss** [comment]
The Vanity URL for the prod deploy is https://smk-clean-bc.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @dgboss, @NicoledeGreef

**Comment by michaelpnelson** [comment]
This resolves #84.

**Pull request merged**
