### PR TITLE
Condensed mobile header

### PR DESCRIPTION
**Pull request by rustyjux**
link to demo deployment of your smk based app is 
 https://smk-clean-bc-rt-b16795-dev.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @dgboss, @NicoledeGreef

### CODE REVIEW

**Comment by dgboss** [comment]
The Vanity URL for the dev deploy is https://smk-clean-bc-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @dgboss, @NicoledeGreef

**Comment by rustyjux** [comment]
The dev deployment was a bit messed before I submitted this PR - no basemap and no ministry points. Not sure what's going on there.

**Review by michaelpnelson — APPROVED** [review]
This looks fine to me. It looks great across different screen sizes in Developer Tools and on my phone. 480px seems like a reasonable break point; I don't have a better suggestion, and we can update it later if we find reason to.

**Comment by dgboss** [comment]
link to demo deployment of your smk based app is 
 https://smk-clean-bc-rt-b16795-prod.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @dgboss, @NicoledeGreef

**Comment by dgboss** [comment]
The Vanity URL for the prod deploy is https://smk-clean-bc.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @dgboss, @NicoledeGreef

**Pull request merged**
